<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Lthrt\UserBundle\Entity\Role;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadRole extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Role::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $role1              = new Role('ROLE_ADMIN');
        $role1->role        = 'ROLE_ADMIN';
        $role1->description = 'Admin User Role';
        $role1->active      = true;
        $role1->id          = 1;
        $this->addReference('_reference_LthrtEntityBundleRole1', $role1);
        $this->addReference('ROLE_ADMIN', $role1);
        $manager->persist($role1);

        $role2              = new Role('ROLE_USER');
        $role2->role        = 'ROLE_USER';
        $role2->description = 'Normal User Role';
        $role2->active      = true;
        $role2->id          = 2;
        $this->addReference('_reference_LthrtEntityBundleRole2', $role2);
        $this->addReference('ROLE_USER', $role2);
        $manager->persist($role2);

        $role3              = new Role('ROLE_OBSOLETE');
        $role3->role        = 'ROLE_OBSOLETE';
        $role3->description = 'Obsolete Role -- Deactivated';
        $role3->active      = false;
        $role3->id          = 3;
        $this->addReference('ROLE_OBSOLETE', $role3);
        $this->addReference('_reference_LthrtEntityBundleRole3', $role3);
        $manager->persist($role3);

        $role4              = new Role('Delete');
        $role4->role        = 'Delete';
        $role4->description = 'Role to Delete';
        $role4->active      = false;
        $role4->id          = 4;
        $this->addReference('ROLE_DELETE', $role4);
        $this->addReference('_reference_LthrtEntityBundleRole4', $role4);
        $manager->persist($role4);

        $manager->flush();
    }
}
